### PR TITLE
feat: Allow for sharding and replicas

### PR DESCRIPTION
**Pull request by cafuego**
Refs: OPS-8064

### CODE REVIEW

**Comment by orakili** [comment]
The code for RW9 was in the V2 branch which I just merged into `main`.

**Comment by cafuego** [comment]
Good! Do you want to make a release off main HEAD, so we can pin it on RW9?

**Comment by orakili** [comment]
Sorry, didn't see your comment. We could but there is no new code between the latest release [v2.2.4](https://github.com/UN-OCHA/rwint-api-indexer/tree/v2.2.4) (used by RW9) and main aside of the V2 -> Main merge commit.

**Comment by cafuego** [comment]
All good, packagist has v2.2.4 already anyway.

**Pull request merged**
